name: CI Pipeline

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Hadolint
      run: wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 && chmod +x /usr/local/bin/hadolint

    - name: Run Hadolint
      uses: reviewdog/action-hadolint@55be5d2c4b0b80d439247b128a9ded3747f92a29 # pin@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        filter_mode: added
        fail_on_error: true

    - name: Run Yamllint
      uses: reviewdog/action-yamllint@8c429dfe4fc47b1ce1fa99a64e94693880d5dc30 # pin@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        level: warning
        reporter: github-pr-review
        fail_on_error: true

    - name: Run Misspell
      uses: reviewdog/action-misspell@811b1e15f531430be3a5784e3d591bd657df18b0 # pin@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        level: warning
        reporter: github-pr-review
        fail_on_error: true

    - name: Install cpplint
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install cpplint

    - name: Run cpplint
      uses: reviewdog/action-cpplint@a5d486c641b1ae5fd018b4fe6bf7bef3bc6e506e 
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        level: warning
        reporter: github-pr-review
        fail_on_error: true

  diff_check:
    name: Handle Large Diffs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Check Diff Size
      run: |
        DIFF_SIZE=$(git diff --stat | wc -l)
        if [ "$DIFF_SIZE" -gt 300 ]; then
          echo "Diff size exceeds 300 files. Skipping checks."
          exit 0
        fi

